- name: play1
  hosts: local
  connection: local #managing its own node no need of credentials
  tasks:
  - name: "play1 and task1"
    ansible.builtin.debug:
    msg:"install play1 task1"

  - name: play2
    hosts: local
    connection: local   #managing its own node no need of credentials
    tasks:
    - name: "play2 and task2"
      ansible.builtin.debug:
      msg:"install play2 task2"