- name: variables
  hosts: local
  connection: local
  vars:
     COURSE: "devops with aws"
     DURATION: 12hrs
     TRAINER: shivakumar
  tasks:
  - name: print the variable
    ansible.builtin.debug:
       msg: "course is {{COURSE}}, duration {{DURATION}}, trainer is {{TRAINER}}"