- name: variables
  hosts: local
  connection: local
  vars:    #play level variable,global variable
     COURSE: "devops with aws"
     DURATION: 12hrs
     TRAINER: shivakumar
  tasks:
  - name: print the variable
    vars:     #task level variable,accessable with only task.task level variable can overide play level variable.
      COURSE: ansible
    ansible.builtin.debug:
       msg: "course is {{ COURSE }}, duration {{ DURATION }}, trainer is {{ TRAINER }}"

  - name: print the variable
    ansible.builtin.debug:
       msg: "course is {{ COURSE }}, duration {{ DURATION }}, trainer is {{ TRAINER }}"     